version: "3"
services:
  devapp-server:
    image: emission/e-mission-phone.dev.ui-only:4.4.0
    environment:
      - PHONE_REPO=https://github.com/e-mission/e-mission-phone.git
      - PHONE_BRANCH=master
      # CHANGEME: enable this for autoreloading
      # - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    # volumes:
      # specify the host directory where the source code should live
      # If this is ~/e-mission-phone-docker, then you can edit the files at
      # ~/e-mission-phone-docker/e-mission-phone/www/...
      # - ~/e-mission-phone-docker:/src/
      # - CHANGEME:/src/
      # - /tmp/e-mission-phone-docker:/src/
    

